### ISSUE TITLE
pod 'ZIKViper' 之后 编译项目出现错误 

### ISSUE THREAD

**Issue by imaginedays** [Zuikyo/ZIKViper#1]
Undefined symbols for architecture x86_64:
  "___cxa_demangle", referenced from:
      -[NSString(Demangle) demangledAsCPP] in libZIKRouter.a(NSString+Demangle.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      _demangleSymbolAsString(char const*, unsigned long, DemangleOptions const&) in libZIKRouter.a(NSString+Demangle.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      -[NSString(Demangle) demangledAsSwift] in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsSimplifiedSwift] in libZIKRouter.a(NSString+Demangle.o)
  "___gxx_personality_v0", referenced from:
      +[ZIKImageSymbol enumerateImages:] in libZIKRouter.a(ZIKImageSymbol.o)
      +[ZIKImageSymbol findSymbolInImage:name:] in libZIKRouter.a(ZIKImageSymbol.o)
      +[ZIKImageSymbol findSymbolInImage:matching:] in libZIKRouter.a(ZIKImageSymbol.o)
      -[NSString(Demangle) demangledAsSwift] in libZIKRouter.a(NSString+Demangle.o)
      _demangleSymbolAsString(char const*, unsigned long, DemangleOptions const&) in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsSimplifiedSwift] in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsCPP] in libZIKRouter.a(NSString+Demangle.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Zuikyo** [comment]
See [___cxa_demangle ld: symbol(s) not found](https://github.com/Zuikyo/ZIKRouter/issues/10).
`libZIKRouter.a` need to link `libc++.tbd`. I miss to add it as dependency.
I will publish a new version of ZIKRouter to fix it.

**Comment by Zuikyo** [comment]
ZIKRouter 1.0.4 is released, and it's fixed now.
