### ISSUE TITLE
你好 编译不过，怎么体验demo

### ISSUE THREAD

**Issue by jj89757hhb** [Zuikyo/ZIKViper#2]

**Comment by Zuikyo** [comment]
具体是什么错误？

**Comment by jj89757hhb** [comment]
我现在是打开ZIKViperDemo编译 。    #import <ZIKRouter/ZIKViewRouter.h> 这个提示找不到

**Comment by Zuikyo** [comment]
这个仓库使用了 submodule ZIKRouter。你需要同时 clone submodule：

git clone --recursive https://github.com/Zuikyo/ZIKViper.git

**Comment by jj89757hhb** [comment]
嗯 要使用  recursive  。谢谢了

**Comment by Alvazz** [comment]
这个架构，在什么实际项目中使用过吗
