### ISSUE TITLE
请问代码生成模板生成的文件夹是蓝色的，能变成黄色的么？

### ISSUE THREAD

**Issue by imaginedays** [Zuikyo/ZIKViper#3]
![aaa](https://user-images.githubusercontent.com/978747/81652677-b3a91880-9466-11ea-8fa9-cc2577c3b8e0.jpg)

**Comment by Zuikyo** [comment]
还没找到方法，现在只能先移除后再添加文件。

**Comment by imaginedays** [comment]
> 还没找到方法，现在只能先移除后再添加文件。

谢谢。
